//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
    }
}
